# Generated by Django 5.2.5 on 2025-09-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_game_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, help_text='Upload HTML game file', null=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, help_text='External game URL', max_length=255, null=True),
        ),
    ]
